version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdr_php
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: cdr_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cdr_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cdr_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
